export const ingredients = [
  "eggs",
  "milk",
  "sugar",
  "salt",
  "fish",
  "tomatos",
  "basil",
  "beef",
  "pork",
  "chicken",
  "venison",
  "pepper",
  "cumin",
  "oregano",
  "turmeric",
  "curry",
  "potatoes",
  "fries",
  "beans",
  "green-beans",
  "lettuce",
  "coriander",
  "cellery",
  "chicken-wings",
  "pasta",
  "garlic",
  "onion",
  "leak",
  "mushrooms",
  "butter",
  "chocolate chips",
  "flour",
  "beer",
  "batter",
  "dip",
  "crutons",
  "parmesan",
  "olive oil",
  "mustard",
  "anchhovies",
  "cheese",
  "tomato sauce",
  "pepperoni",
  "dough",
];

export const instructions = [
  "boiling",
  "slow-cooking",
  "roasting",
  "skilleting",
  "frying",
  "deep-frying",
  "pressure-cooking",
  "air-frying",
  "marinating",
  "drying",
  "cutting",
  "brining",
  "broiling",
  "simmering",
  "stir-frying",
  "blanching",
  "stewing",
  "mixing",
  "constructing",
];

export const category = ["breakfast", "lunch", "dinner", "desert"];

export const difficulty = ["easy", "medium", "hard"];
